#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/generated/deepseek_host.h"

mkdir -p "$ROOT/generated"

IP="$(curl -fsS --connect-timeout 10 \
  'https://dns.google/resolve?name=api.deepseek.com&type=A' \
  | python3 -c "
import json, sys
d = json.load(sys.stdin)
ips = [a['data'] for a in d.get('Answer', []) if a.get('type') == 1]
if not ips:
    raise SystemExit('no A record for api.deepseek.com')
print(ips[-1])
")"

IFS=. read -r O1 O2 O3 O4 <<<"$IP"
HOST_ORDER=$(( (O1 << 24) + (O2 << 16) + (O3 << 8) + O4 ))

cat >"$OUT" <<EOF
#ifndef DEEPSEEK_HOST_H
#define DEEPSEEK_HOST_H

/* Generated by scripts/mk-deepseek-host.sh — real CloudFront IP (not 198.18.x proxy). */
#define DEEPSEEK_API_IP_HOST  ${HOST_ORDER}UL
#define DEEPSEEK_API_IP_STR   "${IP}"

#endif
EOF

echo "[mk-deepseek-host] api.deepseek.com -> ${IP} (0x$(printf '%08x' "$HOST_ORDER"))"
