#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/generated/deepseek_host.h"

mkdir -p "$ROOT/generated"

parse_doh_json() {
  python3 -c "
import json, sys
try:
    d = json.load(sys.stdin)
    ips = [a['data'] for a in d.get('Answer', []) if a.get('type') == 1]
    if ips:
        print(ips[-1])
except Exception:
    pass
" 2>/dev/null || true
}

read_existing_ip() {
  if [[ ! -f "$OUT" ]]; then
    return 1
  fi
  local ip
  ip="$(grep '#define DEEPSEEK_API_IP_STR' "$OUT" 2>/dev/null \
    | sed -n 's/.*"\([^"]*\)".*/\1/p' | head -1 || true)"
  if [[ -n "$ip" && "$ip" != "0.0.0.0" ]]; then
    echo "$ip"
    return 0
  fi
  return 1
}

resolve_ip() {
  local ip=""

  if command -v dig >/dev/null 2>&1; then
    ip="$(dig +time=5 +tries=1 +short A api.deepseek.com @8.8.8.8 2>/dev/null \
      | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -1 || true)"
    if [[ -n "$ip" ]]; then
      echo "$ip"
      return 0
    fi
  fi

  if command -v host >/dev/null 2>&1; then
    ip="$(host -t A api.deepseek.com 8.8.8.8 2>/dev/null \
      | awk '/has address/ { print $4; exit }' || true)"
    if [[ -n "$ip" ]]; then
      echo "$ip"
      return 0
    fi
  fi

  if command -v nslookup >/dev/null 2>&1; then
    ip="$(nslookup api.deepseek.com 8.8.8.8 2>/dev/null \
      | awk '/^Address: / && $2 !~ /^8\.8\.8\.8/ { print $2; exit }' || true)"
    if [[ -n "$ip" ]]; then
      echo "$ip"
      return 0
    fi
  fi

  ip="$(curl -fsS --connect-timeout 8 \
    'https://dns.google/resolve?name=api.deepseek.com&type=A' 2>/dev/null \
    | parse_doh_json || true)"
  if [[ -n "$ip" ]]; then
    echo "$ip"
    return 0
  fi

  ip="$(curl -fsS --connect-timeout 8 -H 'accept: application/dns-json' \
    'https://1.1.1.1/dns-query?name=api.deepseek.com&type=A' 2>/dev/null \
    | parse_doh_json || true)"
  if [[ -n "$ip" ]]; then
    echo "$ip"
    return 0
  fi

  if ip="$(read_existing_ip)"; then
    echo "$ip"
    return 0
  fi

  echo "0.0.0.0"
  return 0
}

IP="$(resolve_ip)"
WARN=""
if [[ "$IP" == "0.0.0.0" ]]; then
  WARN=" (runtime DNS only — baked IP unused by 0.5.0+)"
fi

IFS=. read -r O1 O2 O3 O4 <<<"$IP"
HOST_ORDER=$(( (O1 << 24) + (O2 << 16) + (O3 << 8) + O4 ))

cat >"$OUT" <<EOF
#ifndef DEEPSEEK_HOST_H
#define DEEPSEEK_HOST_H

/* Generated by scripts/mk-deepseek-host.sh — optional legacy hint (Guest resolves at runtime). */
#define DEEPSEEK_API_IP_HOST  ${HOST_ORDER}UL
#define DEEPSEEK_API_IP_STR   "${IP}"

#endif
EOF

echo "[mk-deepseek-host] api.deepseek.com -> ${IP} (0x$(printf '%08x' "$HOST_ORDER"))${WARN}"
