#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/generated/deepseek_key.h"
ENV_FILE="$ROOT/.env"
KEY=""

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE" 2>/dev/null || true
fi

if [[ -n "${DEEPSEEK_API_KEY:-}" ]]; then
  KEY="$DEEPSEEK_API_KEY"
fi

mkdir -p "$(dirname "$OUT")"
cat >"$OUT" <<EOF
/* generated by scripts/mk-deepseek-key.sh — do not commit secrets */
#ifndef DEEPSEEK_API_KEY
#define DEEPSEEK_API_KEY "$KEY"
#endif
EOF

if [[ -n "$KEY" ]]; then
  echo "[mk-deepseek-key] wrote key (${#KEY} chars) to generated/deepseek_key.h"
else
  echo "[mk-deepseek-key] no DEEPSEEK_API_KEY; native DeepSeek disabled"
fi
